name: ci

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - recette
      - main
  workflow_dispatch:

jobs:
  branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: No operation
        run: echo "Workflow déclenché selon les règles définies."
